//
// List.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** iterable collection of models */

open class List: Codable {

    public var size: Int
    public var startKey: String


    
    public init(size: Int, startKey: String) {
        self.size = size
        self.startKey = startKey
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(size, forKey: "size")
        try container.encode(startKey, forKey: "startKey")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        size = try container.decode(Int.self, forKey: "size")
        startKey = try container.decode(String.self, forKey: "startKey")
    }
}

