//
// ReactionLikeList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** an array of ReactionLike models */

open class ReactionLikeList: Codable {

    public var size: Int
    public var startKey: String
    public var items: [ReactionLike]


    
    public init(size: Int, startKey: String, items: [ReactionLike]) {
        self.size = size
        self.startKey = startKey
        self.items = items
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(size, forKey: "size")
        try container.encode(startKey, forKey: "startKey")
        try container.encode(items, forKey: "items")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        size = try container.decode(Int.self, forKey: "size")
        startKey = try container.decode(String.self, forKey: "startKey")
        items = try container.decode([ReactionLike].self, forKey: "items")
    }
}

