//
// RequestUserListType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum RequestUserListType: String, Codable {
    case leaderboard = "leaderboard"
    case leaderboardWeekly = "leaderboard-weekly"
    case recentReactors = "recent-reactors"
    case followings = "followings"
    case followers = "followers"
    case blocking = "blocking"
    case pendingFollowers = "pending-followers"
    case promoted = "promoted"
    case ids = "ids"

}
