//
// RequestAuthRefreshToken.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Request model for auth/refreshToken endpoint. */

open class RequestAuthRefreshToken: Codable {

    /** The refresh token. */
    public var refreshToken: String


    
    public init(refreshToken: String) {
        self.refreshToken = refreshToken
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(refreshToken, forKey: "refreshToken")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        refreshToken = try container.decode(String.self, forKey: "refreshToken")
    }
}

