//
// RequestReactionListSort.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum RequestReactionListSort: String, Codable {
    case popular = "popular"
    case followings = "followings"
    case latest = "latest"

}
