//
// RequestAuthSignUp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Request model for auth/signUp endpoint. */

open class RequestAuthSignUp: Codable {

    /** Unique username (can be an email address). */
    public var username: String
    /** Password attribute requires numbers, lowercase and uppercase letters. */
    public var password: String
    /** At least one of attributes &#39;email&#39; and &#39;phone&#39; must be specified. */
    public var email: String?
    /** At least one of attributes &#39;email&#39; and &#39;phone&#39; must be specified. */
    public var phone: String?


    
    public init(username: String, password: String, email: String?, phone: String?) {
        self.username = username
        self.password = password
        self.email = email
        self.phone = phone
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(username, forKey: "username")
        try container.encode(password, forKey: "password")
        try container.encodeIfPresent(email, forKey: "email")
        try container.encodeIfPresent(phone, forKey: "phone")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        username = try container.decode(String.self, forKey: "username")
        password = try container.decode(String.self, forKey: "password")
        email = try container.decodeIfPresent(String.self, forKey: "email")
        phone = try container.decodeIfPresent(String.self, forKey: "phone")
    }
}

