//
// TimelineEvent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** TimelineEvent */

open class TimelineEvent: Codable {

    public enum Event: String, Codable { 
        case play = "play"
        case pause = "pause"
    }
    public var reactionTimestamp: Double
    public var contentTimestamp: Double
    public var event: Event


    
    public init(reactionTimestamp: Double, contentTimestamp: Double, event: Event) {
        self.reactionTimestamp = reactionTimestamp
        self.contentTimestamp = contentTimestamp
        self.event = event
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(reactionTimestamp, forKey: "reactionTimestamp")
        try container.encode(contentTimestamp, forKey: "contentTimestamp")
        try container.encode(event, forKey: "event")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        reactionTimestamp = try container.decode(Double.self, forKey: "reactionTimestamp")
        contentTimestamp = try container.decode(Double.self, forKey: "contentTimestamp")
        event = try container.decode(Event.self, forKey: "event")
    }
}

