//
// ReactionCommentList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** an array of ReactionComment models */

open class ReactionCommentList: Codable {

    public var size: RequestListSize
    public var startKey: RequestListStartKey
    public var items: [ReactionComment]


    
    public init(size: RequestListSize, startKey: RequestListStartKey, items: [ReactionComment]) {
        self.size = size
        self.startKey = startKey
        self.items = items
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(size, forKey: "size")
        try container.encode(startKey, forKey: "startKey")
        try container.encode(items, forKey: "items")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        size = try container.decode(RequestListSize.self, forKey: "size")
        startKey = try container.decode(RequestListStartKey.self, forKey: "startKey")
        items = try container.decode([ReactionComment].self, forKey: "items")
    }
}

