//
// ReactionLikesCounts.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class ReactionLikesCounts: Codable {

    public var love: Int64?
    public var lol: Int64?
    public var wow: Int64?
    public var sad: Int64?
    public var angry: Int64?


    
    public init(love: Int64?, lol: Int64?, wow: Int64?, sad: Int64?, angry: Int64?) {
        self.love = love
        self.lol = lol
        self.wow = wow
        self.sad = sad
        self.angry = angry
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(love, forKey: "love")
        try container.encodeIfPresent(lol, forKey: "lol")
        try container.encodeIfPresent(wow, forKey: "wow")
        try container.encodeIfPresent(sad, forKey: "sad")
        try container.encodeIfPresent(angry, forKey: "angry")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        love = try container.decodeIfPresent(Int64.self, forKey: "love")
        lol = try container.decodeIfPresent(Int64.self, forKey: "lol")
        wow = try container.decodeIfPresent(Int64.self, forKey: "wow")
        sad = try container.decodeIfPresent(Int64.self, forKey: "sad")
        angry = try container.decodeIfPresent(Int64.self, forKey: "angry")
    }
}

