//
// RequestAuthForgotPassword.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Request model for auth/forgotPassword endpoint. */

open class RequestAuthForgotPassword: Codable {

    /** Unique username assigned alias (email or phone). */
    public var username: String


    
    public init(username: String) {
        self.username = username
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(username, forKey: "username")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        username = try container.decode(String.self, forKey: "username")
    }
}

