//
// RequestAuthConfirmSignUp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Request model for auth/confirmSignUp endpoint. */

open class RequestAuthConfirmSignUp: Codable {

    /** Unique username (can be an email address). */
    public var username: String
    /** Confirmation code. */
    public var confirmationCode: String
    /** Display name. */
    public var displayname: String?
    public var bio: String?
    public var isPublic: Bool?


    
    public init(username: String, confirmationCode: String, displayname: String?, bio: String?, isPublic: Bool?) {
        self.username = username
        self.confirmationCode = confirmationCode
        self.displayname = displayname
        self.bio = bio
        self.isPublic = isPublic
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(username, forKey: "username")
        try container.encode(confirmationCode, forKey: "confirmationCode")
        try container.encodeIfPresent(displayname, forKey: "displayname")
        try container.encodeIfPresent(bio, forKey: "bio")
        try container.encodeIfPresent(isPublic, forKey: "isPublic")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        username = try container.decode(String.self, forKey: "username")
        confirmationCode = try container.decode(String.self, forKey: "confirmationCode")
        displayname = try container.decodeIfPresent(String.self, forKey: "displayname")
        bio = try container.decodeIfPresent(String.self, forKey: "bio")
        isPublic = try container.decodeIfPresent(Bool.self, forKey: "isPublic")
    }
}

