//
// RequestReactionLikeListType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Request model for &#39;type&#39; parameter of &#39;reaction/like/list&#39; endpoint */
public enum RequestReactionLikeListType: String, Codable {
    case reaction = "reaction"

}
