//
// RequestReactionCommentListType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum RequestReactionCommentListType: String, Codable {
    case reaction = "reaction"

}
