//
// RequestReactionListType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum RequestReactionListType: String, Codable {
    case hot = "hot"
    case following = "following"
    case video = "video"
    case hashtag = "hashtag"
    case user = "user"

}
