//
// RequestVideoListType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum RequestVideoListType: String, Codable {
    case following = "following"
    case personalised = "personalised"
    case trending = "trending"
    case featured = "featured"
    case latest = "latest"
    case hashtag = "hashtag"
    case related = "related"
    case user = "user"
    case youtube = "youtube"
    case facebook = "facebook"
    case instagram = "instagram"

}
