//
// RequestAuthConfirmForgotPassword.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Request model for auth/confirmForgotPassword endpoint. */

open class RequestAuthConfirmForgotPassword: Codable {

    /** Unique username (can be an email address). */
    public var username: String
    /** Confirmation code. */
    public var confirmationCode: String
    /** Password attribute requires numbers, lowercase and uppercase letters. */
    public var password: String


    
    public init(username: String, confirmationCode: String, password: String) {
        self.username = username
        self.confirmationCode = confirmationCode
        self.password = password
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(username, forKey: "username")
        try container.encode(confirmationCode, forKey: "confirmationCode")
        try container.encode(password, forKey: "password")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        username = try container.decode(String.self, forKey: "username")
        confirmationCode = try container.decode(String.self, forKey: "confirmationCode")
        password = try container.decode(String.self, forKey: "password")
    }
}

