//
// RequestAuthChangePassword.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Request model for auth/changePassword endpoint. */

open class RequestAuthChangePassword: Codable {

    /** Old password, must contain at least one number, lowercase and uppercase letter. */
    public var oldPassword: String
    /** New password, must contain at least one number, lowercase and uppercase letter. */
    public var password: String
    /** The access token. */
    public var accessToken: String


    
    public init(oldPassword: String, password: String, accessToken: String) {
        self.oldPassword = oldPassword
        self.password = password
        self.accessToken = accessToken
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(oldPassword, forKey: "oldPassword")
        try container.encode(password, forKey: "password")
        try container.encode(accessToken, forKey: "accessToken")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        oldPassword = try container.decode(String.self, forKey: "oldPassword")
        password = try container.decode(String.self, forKey: "password")
        accessToken = try container.decode(String.self, forKey: "accessToken")
    }
}

