//
// RequestQueryBoolean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum RequestQueryBoolean: String, Codable {
    case _true = "true"
    case _false = "false"
    case _0 = "0"
    case _1 = "1"
    case empty = ""

}
