//
// UserIdReadOnly.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** UserId standardised attribute matching &#39;region_uuid&#39; or &#39;uuid&#39; regex pattern. Can not be updated. */

open class UserIdReadOnly: Codable {



    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

    }
}

